import path from "path";
import fs from "fs-extra";
import { stringify } from "yaml";
import type { Codegraph } from "./types.js";
import { scanModules, listTrackedSourceFiles } from "./scanner.js";
import { detectProjectProfile } from "./profiler.js";

const GENERATOR_VERSION = "1.0.0";
const CODEGRAPH_FILENAME = "_codegraph.yaml";

export interface GenerateCodegraphOptions {
  debug?: boolean;
}

/**
 * Generate the codegraph for a project and write it to `.engraph/_codegraph.yaml`.
 *
 * This is the main entry point called by `init` and `upgrade` commands.
 * The codegraph is a deterministic, auto-generated structural representation
 * of the codebase — no LLM calls, runs in seconds.
 */
export async function generateCodegraph(
  projectPath: string,
  options: GenerateCodegraphOptions = {}
): Promise<Codegraph> {
  const { debug = false } = options;

  // Resolve the commit SHA from git (if available)
  const commitSha = await resolveCommitSha(projectPath);

  if (debug) {
    console.log(`[codegraph] project path: ${projectPath}`);
    console.log(`[codegraph] commit: ${commitSha ?? "none"}`);
  }

  // WP2 — Layer 1: Directory scanner + module tree
  const modules = await scanModules(projectPath, { debug });

  // WP3 — Layer 2: Project profile + entry point detection
  const allFiles = await listTrackedSourceFiles(projectPath);
  const project = await detectProjectProfile(projectPath, allFiles, modules, { debug });

  // TODO: WP4 — Layer 3: Import analysis via tree-sitter WASM
  // TODO: WP5 — Layer 4: Conventional structure + file index

  const codegraph: Codegraph = {
    generated_at: new Date().toISOString(),
    generator_version: GENERATOR_VERSION,
    commit_sha: commitSha,

    project,
    modules,
    dependencies: {
      edges: [],
      core_modules: [],
      leaf_modules: [],
    },
    file_index: {},
  };

  // Write the codegraph to .engraph/_codegraph.yaml
  await writeCodegraph(projectPath, codegraph);

  if (debug) {
    console.log(`[codegraph] written to .engraph/${CODEGRAPH_FILENAME}`);
  }

  return codegraph;
}

/**
 * Write the codegraph YAML to the .engraph directory.
 */
async function writeCodegraph(
  projectPath: string,
  codegraph: Codegraph
): Promise<void> {
  const engraphDir = path.join(projectPath, ".engraph");
  await fs.ensureDir(engraphDir);

  const header = [
    "# Auto-generated by engraph. Do not edit manually.",
    "# Regenerate with: engraph init --here / engraph upgrade",
    "",
  ].join("\n");

  const yamlContent = header + stringify(codegraph, { lineWidth: 120 });
  const outputPath = path.join(engraphDir, CODEGRAPH_FILENAME);
  await fs.writeFile(outputPath, yamlContent, "utf8");
}

/**
 * Resolve the current git HEAD commit SHA, or null if not a git repo.
 */
async function resolveCommitSha(
  projectPath: string
): Promise<string | null> {
  try {
    const { execSync } = await import("child_process");
    const sha = execSync("git rev-parse HEAD", {
      cwd: projectPath,
      encoding: "utf8",
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
    return sha || null;
  } catch {
    return null;
  }
}
