import path from "path";
import fs from "fs-extra";
import { stringify } from "yaml";
import type { Codegraph, Module, ProjectProfile } from "./types.js";

const SUB_GRAPH_BUDGET = 500;

const YAML_HEADER = [
  "# Codegraph — structural map of this codebase, auto-generated by engraph.",
  "# Module IDs are the primary vocabulary for referencing logical units across",
  "# commits, context files, and agent coordination. Use imports/imported_by",
  "# to understand dependency relationships and blast radius of changes.",
  "#",
  "# Regenerate: engraph graph",
  "# Auto-synced: after agent file edits via PostToolUse hooks",
  "# Do not edit manually. Do not version control.",
  "",
].join("\n");

// ─── Module hierarchy ──────────────────────────────────────────────────────

interface ModuleNode {
  module: Module;
  children: ModuleNode[];
}

/**
 * Build a tree from the flat module list using path-based parent-child relationships.
 *
 * A module is a child of another if its ID starts with the parent's ID + "/",
 * and there is no closer intermediate parent.
 *
 * Example: given IDs ["commands", "commands/graph", "commands/init", "utils"]
 *   - "commands" has children ["commands/graph", "commands/init"]
 *   - "utils" has no children
 *   - Top-level: ["commands", "utils"] (plus any without a parent in the list)
 */
function buildModuleTree(modules: Module[]): ModuleNode[] {
  // Sort by ID so parents come before children
  const sorted = [...modules].sort((a, b) => a.id.localeCompare(b.id));
  const nodeMap = new Map<string, ModuleNode>();

  for (const mod of sorted) {
    nodeMap.set(mod.id, { module: mod, children: [] });
  }

  const topLevel: ModuleNode[] = [];

  for (const mod of sorted) {
    const parentId = findParentId(mod.id, nodeMap);
    if (parentId) {
      nodeMap.get(parentId)!.children.push(nodeMap.get(mod.id)!);
    } else {
      topLevel.push(nodeMap.get(mod.id)!);
    }
  }

  return topLevel;
}

/**
 * Find the closest parent module ID for a given module ID.
 * Walk up the path segments looking for an existing module.
 */
function findParentId(moduleId: string, nodeMap: Map<string, ModuleNode>): string | null {
  const segments = moduleId.split("/");
  // Walk from the immediate parent upward
  for (let i = segments.length - 1; i > 0; i--) {
    const candidate = segments.slice(0, i).join("/");
    if (nodeMap.has(candidate)) {
      return candidate;
    }
  }
  return null;
}

// ─── Line counting ─────────────────────────────────────────────────────────

/**
 * Estimate the YAML line count for a single module entry (without children).
 */
function estimateModuleLines(mod: Module): number {
  const yaml = stringify({ modules: [stripSubGraph(mod)] }, { lineWidth: 120 });
  return yaml.split("\n").length;
}

/**
 * Estimate total lines for a list of modules serialized together.
 */
function estimateGroupLines(nodes: ModuleNode[]): number {
  const modules = nodes.map((n) => stripSubGraph(n.module));
  const yaml = stringify({ modules }, { lineWidth: 120 });
  return yaml.split("\n").length;
}

/**
 * Return a module object without the sub_graph field (for line estimation).
 */
function stripSubGraph(mod: Module): Omit<Module, "sub_graph"> {
  const { sub_graph, ...rest } = mod;
  return rest;
}

// ─── Recursive serializer ──────────────────────────────────────────────────

/**
 * Write the codegraph to a recursive codegraph/ directory structure.
 *
 * Root codegraph/index.yaml is always a single file with all top-level modules.
 * Sub-graphs are created when children at a given level exceed the line budget.
 */
export async function writeCodegraph(
  projectPath: string,
  codegraph: Codegraph
): Promise<void> {
  const codegraphDir = path.join(projectPath, ".engraph", "codegraph");

  // Clean the entire codegraph directory before writing fresh output
  await fs.remove(codegraphDir);
  await fs.ensureDir(codegraphDir);

  const tree = buildModuleTree(codegraph.modules);

  // Root index.yaml — always a single file, never split
  const rootModules = serializeLevel(tree, codegraphDir, "codegraph");
  const rootContent = {
    generated_at: codegraph.generated_at,
    generator_version: codegraph.generator_version,
    commit_sha: codegraph.commit_sha,
    project: codegraph.project,
    modules: rootModules,
  };

  const yamlContent = YAML_HEADER + stringify(rootContent, { lineWidth: 120 });
  await fs.writeFile(path.join(codegraphDir, "index.yaml"), yamlContent, "utf8");
}

/**
 * Serialize a level of the module tree. For each node, decide whether to
 * inline its children or split them into a sub-graph.
 *
 * Returns the module entries for this level (with sub_graph set where needed).
 */
function serializeLevel(
  nodes: ModuleNode[],
  codegraphDir: string,
  codegraphRelPrefix: string
): Module[] {
  const result: Module[] = [];

  for (const node of nodes) {
    if (node.children.length === 0) {
      // Leaf module — always inline
      result.push(stripSubGraphField(node.module));
    } else {
      // Module with children — check if inlining children exceeds budget
      const childLines = estimateGroupLines(node.children);

      if (childLines <= SUB_GRAPH_BUDGET) {
        // Inline: add this module + recursively inline children
        result.push(stripSubGraphField(node.module));
        const inlinedChildren = serializeLevel(node.children, codegraphDir, codegraphRelPrefix);
        result.push(...inlinedChildren);
      } else {
        // Split: create a sub-graph for this module's children
        const subDir = path.join(codegraphDir, node.module.id);
        const subRelPath = `${codegraphRelPrefix}/${node.module.id}/index.yaml`;

        // Write sub-graph index.yaml
        writeSubGraph(node.children, subDir, `${codegraphRelPrefix}/${node.module.id}`);

        // Add parent module with sub_graph reference
        result.push({ ...stripSubGraphField(node.module), sub_graph: subRelPath });
      }
    }
  }

  return result;
}

/**
 * Write a sub-graph index.yaml for a set of child module nodes.
 */
function writeSubGraph(
  nodes: ModuleNode[],
  subDir: string,
  codegraphRelPrefix: string
): void {
  fs.ensureDirSync(subDir);

  const modules = serializeLevel(nodes, path.dirname(subDir), codegraphRelPrefix);
  const content = { modules };
  const yaml = YAML_HEADER + stringify(content, { lineWidth: 120 });
  fs.writeFileSync(path.join(subDir, "index.yaml"), yaml, "utf8");
}

/**
 * Return a module without the sub_graph field (clean serialization).
 */
function stripSubGraphField(mod: Module): Module {
  const { sub_graph, ...rest } = mod;
  return rest as Module;
}
