import path from "path";
import fs from "fs-extra";
import { stringify } from "yaml";
import type { Codegraph, Module, ProjectProfile } from "./types.js";

const SUB_GRAPH_BUDGET = 500;

const YAML_HEADER = [
  "# Codegraph — structural map of this codebase, auto-generated by engraph.",
  "# Module IDs are the primary vocabulary for referencing logical units across",
  "# commits, context files, and agent coordination. Use imports/imported_by",
  "# to understand dependency relationships and blast radius of changes.",
  "#",
  "# Regenerate: engraph graph",
  "# Auto-synced: after agent file edits via PostToolUse hooks",
  "# Do not edit manually. Do not version control.",
  "",
].join("\n");

// ─── Module hierarchy ──────────────────────────────────────────────────────

interface ModuleNode {
  module: Module;
  children: ModuleNode[];
}

/**
 * Build a tree from the flat module list using path-based parent-child relationships.
 *
 * A module is a child of another if its ID starts with the parent's ID + "/",
 * and there is no closer intermediate parent.
 *
 * Example: given IDs ["commands", "commands/graph", "commands/init", "utils"]
 *   - "commands" has children ["commands/graph", "commands/init"]
 *   - "utils" has no children
 *   - Top-level: ["commands", "utils"] (plus any without a parent in the list)
 */
function buildModuleTree(modules: Module[]): ModuleNode[] {
  // Sort by ID so parents come before children
  const sorted = [...modules].sort((a, b) => a.id.localeCompare(b.id));
  const nodeMap = new Map<string, ModuleNode>();

  for (const mod of sorted) {
    nodeMap.set(mod.id, { module: mod, children: [] });
  }

  const topLevel: ModuleNode[] = [];

  for (const mod of sorted) {
    const parentId = findParentId(mod.id, nodeMap);
    if (parentId) {
      nodeMap.get(parentId)!.children.push(nodeMap.get(mod.id)!);
    } else {
      topLevel.push(nodeMap.get(mod.id)!);
    }
  }

  return topLevel;
}

/**
 * Find the closest parent module ID for a given module ID.
 * Walk up the path segments looking for an existing module.
 */
function findParentId(moduleId: string, nodeMap: Map<string, ModuleNode>): string | null {
  const segments = moduleId.split("/");
  // Walk from the immediate parent upward
  for (let i = segments.length - 1; i > 0; i--) {
    const candidate = segments.slice(0, i).join("/");
    if (nodeMap.has(candidate)) {
      return candidate;
    }
  }
  return null;
}

// ─── Line counting ─────────────────────────────────────────────────────────

/**
 * Estimate the YAML line count for a single module entry (without children).
 */
function estimateModuleLines(mod: Module): number {
  const yaml = stringify({ modules: [stripSubGraph(mod)] }, { lineWidth: 120 });
  return yaml.split("\n").length;
}

/**
 * Estimate total lines for a list of modules serialized together.
 */
function estimateGroupLines(nodes: ModuleNode[]): number {
  const modules = nodes.map((n) => stripSubGraph(n.module));
  const yaml = stringify({ modules }, { lineWidth: 120 });
  return yaml.split("\n").length;
}

/**
 * Return a module object without the sub_graph field (for line estimation).
 */
function stripSubGraph(mod: Module): Omit<Module, "sub_graph"> {
  const { sub_graph, ...rest } = mod;
  return rest;
}

// ─── Recursive serializer ──────────────────────────────────────────────────

/**
 * Write the codegraph to a recursive codegraph/ directory structure.
 *
 * Root codegraph/index.yaml contains only level-0 modules. Any level-0 module
 * with children always gets a sub_graph — children never appear in the root file.
 *
 * At deeper levels, the 500-line budget determines whether to further split:
 * children are inlined into the sub-graph file unless doing so exceeds the budget.
 */
export async function writeCodegraph(
  projectPath: string,
  codegraph: Codegraph
): Promise<void> {
  const codegraphDir = path.join(projectPath, ".engraph", "codegraph");

  // Clean the entire codegraph directory before writing fresh output
  await fs.remove(codegraphDir);
  await fs.ensureDir(codegraphDir);

  const tree = buildModuleTree(codegraph.modules);

  // Root index.yaml — only level-0 modules, children always split out
  const rootModules = serializeRootLevel(tree, codegraphDir);
  const rootContent = {
    generated_at: codegraph.generated_at,
    generator_version: codegraph.generator_version,
    commit_sha: codegraph.commit_sha,
    project: codegraph.project,
    modules: rootModules,
  };

  const yamlContent = YAML_HEADER + stringify(rootContent, { lineWidth: 120 });
  await fs.writeFile(path.join(codegraphDir, "index.yaml"), yamlContent, "utf8");
}

/**
 * Serialize root level: every module with children gets a sub_graph — always.
 * Children never appear in the root file.
 */
function serializeRootLevel(
  nodes: ModuleNode[],
  codegraphDir: string
): Module[] {
  const result: Module[] = [];

  for (const node of nodes) {
    if (node.children.length === 0) {
      result.push(stripSubGraphField(node.module));
    } else {
      // Always split children into a sub-graph at root level
      const subDir = path.join(codegraphDir, node.module.id);
      const subRelPath = `codegraph/${node.module.id}/index.yaml`;

      writeSubGraph(node.children, subDir, `codegraph/${node.module.id}`);
      result.push({ ...stripSubGraphField(node.module), sub_graph: subRelPath });
    }
  }

  return result;
}

/**
 * Serialize a sub-graph level. For each node with children, check whether
 * inlining them would push this file over the line budget. If so, split
 * them into a deeper sub-graph. Otherwise, inline them in this file.
 */
function serializeSubLevel(
  nodes: ModuleNode[],
  codegraphDir: string,
  codegraphRelPrefix: string
): Module[] {
  const result: Module[] = [];

  for (const node of nodes) {
    if (node.children.length === 0) {
      result.push(stripSubGraphField(node.module));
    } else {
      // Check if inlining all descendants would exceed the budget
      const allDescendants = collectDescendants(node);
      const inlinedLines = estimateGroupLines(allDescendants);

      if (inlinedLines <= SUB_GRAPH_BUDGET) {
        // Inline: add this module + all descendants in this file
        result.push(stripSubGraphField(node.module));
        const inlinedChildren = serializeSubLevel(node.children, codegraphDir, codegraphRelPrefix);
        result.push(...inlinedChildren);
      } else {
        // Split: create a deeper sub-graph
        const subDir = path.join(codegraphDir, node.module.id);
        const subRelPath = `${codegraphRelPrefix}/${node.module.id}/index.yaml`;

        writeSubGraph(node.children, subDir, `${codegraphRelPrefix}/${node.module.id}`);
        result.push({ ...stripSubGraphField(node.module), sub_graph: subRelPath });
      }
    }
  }

  return result;
}

/**
 * Collect all descendant nodes (flattened) for line estimation.
 */
function collectDescendants(node: ModuleNode): ModuleNode[] {
  const result: ModuleNode[] = [];
  for (const child of node.children) {
    result.push(child);
    result.push(...collectDescendants(child));
  }
  return result;
}

/**
 * Write a sub-graph index.yaml for a set of child module nodes.
 * Uses budget-based splitting for deeper levels.
 */
function writeSubGraph(
  nodes: ModuleNode[],
  subDir: string,
  codegraphRelPrefix: string
): void {
  fs.ensureDirSync(subDir);

  const modules = serializeSubLevel(nodes, path.dirname(subDir), codegraphRelPrefix);
  const content = { modules };
  const yaml = YAML_HEADER + stringify(content, { lineWidth: 120 });
  fs.writeFileSync(path.join(subDir, "index.yaml"), yaml, "utf8");
}

/**
 * Return a module without the sub_graph field (clean serialization).
 */
function stripSubGraphField(mod: Module): Module {
  const { sub_graph, ...rest } = mod;
  return rest as Module;
}
